In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib

import requests
from requests.auth import HTTPBasicAuth
from io import StringIO
%matplotlib inline

In [2]:
import chart_studio.plotly as py
import cufflinks as cf
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from plotly.offline import download_plotlyjs, init_notebook_mode,iplot, plot
init_notebook_mode(connected=True)
cf.go_offline()

In [3]:
url = 'https://hmis.health.go.ug/api/29/analytics.csv?dimension=dx:XXZZbU4B2N3;gtWYJAUCW5C;UvXn8H6o487;KAQG7cbFHFA;P1MyPWVxi5T;idXOxt69W0e;bRYoCXTmJCB;Cw3RNymXWjr;TvqHbq8AKc7;npIzs2n622e;WeT4t43xsmT;bWKt8wPieZ9;a2xhxsTVET3;V9VrETz61yN;Nv9r51u568q;Tm7KefYxbWj;FvoFQ8MKWYz;NF20WeqeY8B;vj1YkrDXVUv;bTrQT7XJULv;DXLXok80AIj;hCRvkCwYdvt;DM0iRlEZHKC;hCED8FhuM7S;AsewPyxdNdf;CGWRNOSVEsk;CedUmoEkMFI;D9fECoo4MRN;FW0bnz2WX4c;xvcx2X32983;HCZEYPfoZ7r;LSrwJqzz8h4;Pg8NJzaXQPP;HWsIOGrZuee;OTlyw79GLSO;ywfVj7F30Ts;JadBi8s2DMg;GMdWrlWwh1w;eniuevNt9Cj;QgHSEKZAkiI;LiSyn6bblsc;r4fQVHDftNs;G3qsihJWUFM;HiwMSf39nhM;ZKUeHDVwJm9;fvsym3Qyfm8&dimension=pe:202001;202002;202003;202004;202005;202006;202007;202008;202009;202010;202011;202012;202101;202102;202103;202104;202105;202106;202107;202108;202109;202110;202111;202112;202201;202202;202203&filter=ou:akV6429SUqu&displayProperty=NAME&tableLayout=true&columns=dx&rows=pe'

In [4]:
result = requests.get(url, auth = HTTPBasicAuth('moh-dhi.payebazibwe', 'Dhis@2022'))
# result = requests.get(url, auth = HTTPBasicAuth('moh-dhi.olukae', 'Olukae774!'))

In [5]:
CEHS_all = pd.read_csv(StringIO(result.text))

In [6]:
# CEHS_all = pd.read_csv(r'C:\Users\dell\Desktop\monthly\JK Input CEHS All.csv')
CEHS_all

,periodid,periodname,periodcode,perioddescription,105-MA14a. Mothers who initiated breastfeeding within the 1st hour after delivery - Total,105-FH01. Number HIV+ FP Users,105-CH03. Deworming (1st Dose),105-CH04. Deworming (2nd Dose),105-MA04b2. Deliveries in unit -Live births - less than 2.5kg,105-MA04a. Deliveries in unit - Total,...,105-CD13. Severe Pneumonia,105-EP13. Severe Acute Respiratory Infection (SARI),105-PT04. Chronic respiratory diseases,105-EP05. Dysentery,105-CD01. Diarrhoea - Acute,105-EP15. Typhoid Fever,108-CV01a. Hypertension (newly diagnosed cases) (Cases),108-CV01b. Hypertension (newly diagnosed cases) (Deaths),105-CV03. Heart failure,105-ES09d. Death at unit - Surgical emergencies
0,202001,January 2020,202001,NaN,88221.0,7891.0,185394.0,99154.0,5833.0,98115.0,...,6375.0,4520.0,1249.0,4122.0,109705.0,15887.0,1133.0,44.0,983.0,235.0
1,202002,February 2020,202002,NaN,83606.0,7123.0,220445.0,97698.0,5376.0,93239.0,...,4799.0,4254.0,782.0,4181.0,124503.0,14999.0,916.0,17.0,1318.0,452.0
2,202003,March 2020,202003,NaN,90102.0,7372.0,241549.0,89938.0,6674.0,98193.0,...,6238.0,5172.0,1125.0,4646.0,113343.0,14789.0,849.0,37.0,1272.0,265.0
3,202004,April 2020,202004,NaN,83622.0,5974.0,677862.0,353076.0,5481.0,90886.0,...,4274.0,2675.0,622.0,3934.0,87269.0,11493.0,868.0,79.0,1001.0,175.0
4,202005,May 2020,202005,NaN,89309.0,7672.0,426382.0,228375.0,5848.0,99407.0,...,3939.0,2046.0,586.0,3911.0,103404.0,13551.0,1076.0,27.0,1113.0,241.0
5,202006,June 2020,202006,NaN,88540.0,7965.0,432572.0,196639.0,6048.0,99028.0,...,5505.0,2272.0,777.0,3365.0,102011.0,15095.0,995.0,35.0,1589.0,433.0
6,202007,July 2020,202007,NaN,95045.0,8643.0,390125.0,133429.0,5842.0,103141.0,...,3731.0,1504.0,782.0,3161.0,99894.0,15491.0,1144.0,38.0,1387.0,259.0
7,202008,August 2020,202008,NaN,96057.0,7691.0,309477.0,139645.0,6356.0,107624.0,...,20123.0,1861.0,637.0,3483.0,105691.0,14582.0,1014.0,19.0,1064.0,266.0
8,202009,September 2020,202009,NaN,100869.0,8574.0,311311.0,160715.0,6065.0,113638.0,...,4084.0,1801.0,829.0,3753.0,104346.0,15929.0,882.0,19.0,1432.0,336.0
9,202010,October 2020,202010,NaN,101314.0,10177.0,5233173.0,2359998.0,8727.0,111853.0,...,4792.0,2239.0,814.0,4191.0,107871.0,16468.0,1087.0,24.0,1693.0,125.0
10,202011,November 2020,202011,NaN,98582.0,7649.0,658015.0,307961.0,5509.0,108755.0,...,5115.0,2690.0,1972.0,4265.0,112170.0,17070.0,1004.0,35.0,959.0,129.0
11,202012,December 2020,202012,NaN,97354.0,6970.0,319144.0,176414.0,5368.0,107167.0,...,5043.0,3227.0,1297.0,4039.0,306481.0,17623.0,894.0,19.0,1168.0,453.0
12,202101,January 2021,202101,NaN,94196.0,8903.0,288973.0,229236.0,5484.0,105578.0,...,5657.0,2573.0,511.0,4177.0,106099.0,15146.0,1011.0,28.0,1411.0,130.0
13,202102,February 2021,202102,NaN,93580.0,7408.0,320435.0,191841.0,5334.0,103862.0,...,5117.0,2455.0,805.0,4759.0,107926.0,13940.0,1022.0,26.0,1401.0,163.0
14,202103,March 2021,202103,NaN,105206.0,8194.0,332136.0,200976.0,6107.0,117454.0,...,4659.0,2264.0,1023.0,5201.0,116223.0,14479.0,1049.0,26.0,1450.0,175.0
15,202104,April 2021,202104,NaN,106469.0,7114.0,3964626.0,2438796.0,6074.0,117431.0,...,4669.0,2707.0,1905.0,4591.0,118357.0,14544.0,1194.0,42.0,1841.0,179.0
16,202105,May 2021,202105,NaN,110691.0,6881.0,712135.0,392289.0,5709.0,122249.0,...,6857.0,4081.0,2193.0,6106.0,117276.0,18994.0,1132.0,46.0,2245.0,125.0
17,202106,June 2021,202106,NaN,100685.0,7370.0,337049.0,191676.0,5978.0,112615.0,...,7701.0,6945.0,2093.0,3619.0,107968.0,20621.0,1039.0,53.0,1176.0,99.0
18,202107,July 2021,202107,NaN,105605.0,7005.0,326673.0,174047.0,6010.0,117541.0,...,4125.0,3669.0,1031.0,2947.0,85981.0,15505.0,1043.0,33.0,1015.0,86.0
19,202108,August 2021,202108,NaN,110336.0,13390.0,363655.0,193255.0,5933.0,123271.0,...,4022.0,3294.0,1241.0,3041.0,83790.0,26483.0,1001.0,26.0,1374.0,117.0
20,202109,September 2021,202109,NaN,118508.0,8706.0,330795.0,182626.0,6023.0,127579.0,...,6620.0,2606.0,1947.0,3227.0,82354.0,13742.0,919.0,19.0,1211.0,109.0
21,202110,October 2021,202110,NaN,114402.0,6758.0,4372060.0,11808128.0,5781.0,125847.0,...,4219.0,2798.0,1197.0,3322.0,89846.0,14776.0,1025.0,31.0,1478.0,242.0
22,202111,November 2021,202111,NaN,110741.0,8144.0,679360.0,483600.0,6303.0,120996.0,...,4843.0,2285.0,2868.0,3220.0,96254.0,15511.0,917.0,49.0,1548.0,545.0
23,202112,December 2021,202112,NaN,108903.0,5864.0,1420414.0,947791.0,6086.0,120772.0,...,5647.0,9144.0,886.0,3257.0,92925.0,19309.0,1038.0,80.0,1083.0,965.0
24,202201,January 2022,202201,NaN,107756.0,6832.0,1468551.0,851734.0,5777.0,119895.0,...,4621.0,6145.0,1044.0,3000.0,92751.0,18333.0,1175.0,42.0,2041.0,394.0
25,202202,February 2022,202202,NaN,100556.0,8155.0,474639.0,298847.0,5286.0,112456.0,...,5704.0,4403.0,1238.0,3778.0,101948.0,15520.0,1091.0,22.0,1261.0,401.0
26,202203,March 2022,202203,NaN,89804.0,6142.0,396547.0,241637.0,5360.0,98568.0,...,6527.0,4509.0,1079.0,3923.0,104061.0,17020.0,632.0,11.0,3967.0,72.0

In [7]:
CEHS_all = CEHS_all.fillna(0)

In [8]:
CEHS_all.rename(columns={'105-MA14a. Mothers who initiated breastfeeding within the 1st hour after delivery - Total':'Mothers_who_initiated_breastfeeding_within_the_1st_hour_after_delivery_Total',
                             '105-FH01. Number HIV+ FP Users':'Number_HIV_Positive_FP_Users',
                             '105-CH03. Deworming (1st Dose)':'Deworming_1st_Dose',
                             '105-CH04. Deworming (2nd Dose)':'Deworming_2nd_Dose',
                             '105-MA04b2. Deliveries in unit -Live births - less than 2.5kg':'Deliveries_in_unit_Live_births_less_than_2_5kg',
                             '105-MA04a. Deliveries in unit - Total':'Deliveries_in_unit_Total',
                             '105-IN03. Injuries due to Gender based violence':'Injuries_due_to_Gender_based_violence',
                             '105-CD05. Sexually Transmitted Infection due to Sexual Gender Based Violence':'STI_due_to_Sexual_Gender_Based_Violence',
                             '105-MC01. Abortions due to Gender-Based Violence (GBV)':'Abortions_due_to_GBV',
                             '105-MH01. Anxiety Disorders':'Anxiety_Disorders',
                             '105-MH02. Anxiety Disorder due to gender based violence':'Anxiety_Disorder_due_to_gender_based_violence',
                             '105-MH03. Unipolar Depressive Disorder':'Unipolar_Depressive_Disorder',
                             '105-MH04. Bipolar disorder':'Bipolar_disorder',
                             '105-MH16. Alcohol Use Disorder':'Alcohol_Use_Disorder',
                             '105-MH17. Substance (Drug) use Disorder':'Substance_Drug_use_Disorder',
                             '105-RB02. Tobacco use':'Tobacco_use',
                             '105-ES01. Number of emergency cases at the facility':'Number_of_emergency_cases_at_the_facility',
                             '105-ES02. Patients that receive care at the scene of emergency':'Patients_that_receive_care_at_the_scene_of_emergency',
                             '105-ES03. Emergency cases that arrive at the facility using an Ambulance':'Emergency_cases_that_arrive_at_the_facility_using_an_Ambulance',
                             '105-ES05. Number of patients accessing emergency unit with 1hr in an emergency unit':'Number_of_patients_accessing_emergency_unit_with_1hr_in_an_emergency_unit',
                             '105-ES10. Total number of Deaths in Emergency Unit':'Total_number_of_Deaths_in_Emergency_Unit',
                             '105-ES09a. Death at unit - Medical emergencies':'Death_at_unit_Medical_emergencies',
                             '105-ES09b. Death at unit - Obstetrics/gynaecology emergencies':'Death_at_unit_Obstetrics_gynaecology_emergencies',
                             '105-ES09c. Death at unit - Paediatric emergencies':'Death_at_unit_Paediatric_emergencies',
                             '105-ES09e. Death at unit - Road traffic Injuries':'Death_at_unit_Road_traffic_Injuries',
                             '105-ES09g. Death at unit - Poisoning':'Death_at_unit_Poisoning',
                             '108-CV03a. Stroke/Cardiovascular Accident(CVA) (Cases)':'CVA_Cases',
                             '108-CV03b. Stroke/Cardiovascular Accident(CVA) (Deaths)':'CVA_Deaths',
                             '108-CV04a. Heart failure (Cases)':'Heart_failure_Cases',
                             '108-CV04b. Heart failure (Deaths)':'Heart_failure_Deaths',
                             '105-ES09f. Death at unit - Burns':'Death_at_unit_Burns',
                             '108-EM01a.1. Diabetes mellitus (newly diagnosed cases) (Cases)':'Diabetes_mellitus_newly_diagnosed_Cases',
                             '108-EM01a.2. Diabetes mellitus (newly diagnosed cases) (Deaths)':'Diabetes_mellitus_newly_diagnosed_Deaths',
                             '108-EM01b.1. Diabetes mellitus (re-attendances) (Cases)':'Diabetes_mellitus_newly_re_attendances_Cases',
                             '108-EM01b.2. Diabetes mellitus (re-attendances) (Deaths)':'Diabetes_mellitus_newly_re_attendances_Deaths',
                             '105-CD12. Pneumonia':'Pneumonia',
                             '105-CD13. Severe Pneumonia':'Severe_Pneumonia',
                             '105-EP13. Severe Acute Respiratory Infection (SARI)':'Severe_Acute_Respiratory_Infection_SARI',
                             '105-PT04. Chronic respiratory diseases':'Chronic_respiratory_diseases',
                             '105-EP05. Dysentery':'Dysentery',
                             '105-CD01. Diarrhoea -  Acute':'Diarrhoea_Acute',
                             '105-EP15. Typhoid Fever':'Typhoid_Fever',
                             '108-CV01a. Hypertension (newly diagnosed cases) (Cases)':'Hypertension_newly_diagnosed_cases_Cases',
                             '108-CV01b. Hypertension (newly diagnosed cases) (Deaths)':'Hypertension_newly_diagnosed_cases_Deaths',
                             '105-CV03. Heart failure':'Heart_failure',
                             '105-ES09d. Death at unit - Surgical emergencies':'Death_at_unit_Surgical_emergencies'
                          }, 
                  inplace=True)

In [9]:
CEHS_all['period'] = pd.to_datetime(CEHS_all['periodname'])
CEHS_all['month_year'] = CEHS_all['period'].dt.strftime('%b-%Y')

In [10]:
CEHS_all_cap = CEHS_all.copy()

In [11]:
CEHS_all_cap

,periodid,periodname,periodcode,perioddescription,Mothers_who_initiated_breastfeeding_within_the_1st_hour_after_delivery_Total,Number_HIV_Positive_FP_Users,Deworming_1st_Dose,Deworming_2nd_Dose,Deliveries_in_unit_Live_births_less_than_2_5kg,Deliveries_in_unit_Total,...,Chronic_respiratory_diseases,Dysentery,Diarrhoea_Acute,Typhoid_Fever,Hypertension_newly_diagnosed_cases_Cases,Hypertension_newly_diagnosed_cases_Deaths,Heart_failure,Death_at_unit_Surgical_emergencies,period,month_year
0,202001,January 2020,202001,0.0,88221.0,7891.0,185394.0,99154.0,5833.0,98115.0,...,1249.0,4122.0,109705.0,15887.0,1133.0,44.0,983.0,235.0,2020-01-01,Jan-2020
1,202002,February 2020,202002,0.0,83606.0,7123.0,220445.0,97698.0,5376.0,93239.0,...,782.0,4181.0,124503.0,14999.0,916.0,17.0,1318.0,452.0,2020-02-01,Feb-2020
2,202003,March 2020,202003,0.0,90102.0,7372.0,241549.0,89938.0,6674.0,98193.0,...,1125.0,4646.0,113343.0,14789.0,849.0,37.0,1272.0,265.0,2020-03-01,Mar-2020
3,202004,April 2020,202004,0.0,83622.0,5974.0,677862.0,353076.0,5481.0,90886.0,...,622.0,3934.0,87269.0,11493.0,868.0,79.0,1001.0,175.0,2020-04-01,Apr-2020
4,202005,May 2020,202005,0.0,89309.0,7672.0,426382.0,228375.0,5848.0,99407.0,...,586.0,3911.0,103404.0,13551.0,1076.0,27.0,1113.0,241.0,2020-05-01,May-2020
5,202006,June 2020,202006,0.0,88540.0,7965.0,432572.0,196639.0,6048.0,99028.0,...,777.0,3365.0,102011.0,15095.0,995.0,35.0,1589.0,433.0,2020-06-01,Jun-2020
6,202007,July 2020,202007,0.0,95045.0,8643.0,390125.0,133429.0,5842.0,103141.0,...,782.0,3161.0,99894.0,15491.0,1144.0,38.0,1387.0,259.0,2020-07-01,Jul-2020
7,202008,August 2020,202008,0.0,96057.0,7691.0,309477.0,139645.0,6356.0,107624.0,...,637.0,3483.0,105691.0,14582.0,1014.0,19.0,1064.0,266.0,2020-08-01,Aug-2020
8,202009,September 2020,202009,0.0,100869.0,8574.0,311311.0,160715.0,6065.0,113638.0,...,829.0,3753.0,104346.0,15929.0,882.0,19.0,1432.0,336.0,2020-09-01,Sep-2020
9,202010,October 2020,202010,0.0,101314.0,10177.0,5233173.0,2359998.0,8727.0,111853.0,...,814.0,4191.0,107871.0,16468.0,1087.0,24.0,1693.0,125.0,2020-10-01,Oct-2020
10,202011,November 2020,202011,0.0,98582.0,7649.0,658015.0,307961.0,5509.0,108755.0,...,1972.0,4265.0,112170.0,17070.0,1004.0,35.0,959.0,129.0,2020-11-01,Nov-2020
11,202012,December 2020,202012,0.0,97354.0,6970.0,319144.0,176414.0,5368.0,107167.0,...,1297.0,4039.0,306481.0,17623.0,894.0,19.0,1168.0,453.0,2020-12-01,Dec-2020
12,202101,January 2021,202101,0.0,94196.0,8903.0,288973.0,229236.0,5484.0,105578.0,...,511.0,4177.0,106099.0,15146.0,1011.0,28.0,1411.0,130.0,2021-01-01,Jan-2021
13,202102,February 2021,202102,0.0,93580.0,7408.0,320435.0,191841.0,5334.0,103862.0,...,805.0,4759.0,107926.0,13940.0,1022.0,26.0,1401.0,163.0,2021-02-01,Feb-2021
14,202103,March 2021,202103,0.0,105206.0,8194.0,332136.0,200976.0,6107.0,117454.0,...,1023.0,5201.0,116223.0,14479.0,1049.0,26.0,1450.0,175.0,2021-03-01,Mar-2021
15,202104,April 2021,202104,0.0,106469.0,7114.0,3964626.0,2438796.0,6074.0,117431.0,...,1905.0,4591.0,118357.0,14544.0,1194.0,42.0,1841.0,179.0,2021-04-01,Apr-2021
16,202105,May 2021,202105,0.0,110691.0,6881.0,712135.0,392289.0,5709.0,122249.0,...,2193.0,6106.0,117276.0,18994.0,1132.0,46.0,2245.0,125.0,2021-05-01,May-2021
17,202106,June 2021,202106,0.0,100685.0,7370.0,337049.0,191676.0,5978.0,112615.0,...,2093.0,3619.0,107968.0,20621.0,1039.0,53.0,1176.0,99.0,2021-06-01,Jun-2021
18,202107,July 2021,202107,0.0,105605.0,7005.0,326673.0,174047.0,6010.0,117541.0,...,1031.0,2947.0,85981.0,15505.0,1043.0,33.0,1015.0,86.0,2021-07-01,Jul-2021
19,202108,August 2021,202108,0.0,110336.0,13390.0,363655.0,193255.0,5933.0,123271.0,...,1241.0,3041.0,83790.0,26483.0,1001.0,26.0,1374.0,117.0,2021-08-01,Aug-2021
20,202109,September 2021,202109,0.0,118508.0,8706.0,330795.0,182626.0,6023.0,127579.0,...,1947.0,3227.0,82354.0,13742.0,919.0,19.0,1211.0,109.0,2021-09-01,Sep-2021
21,202110,October 2021,202110,0.0,114402.0,6758.0,4372060.0,11808128.0,5781.0,125847.0,...,1197.0,3322.0,89846.0,14776.0,1025.0,31.0,1478.0,242.0,2021-10-01,Oct-2021
22,202111,November 2021,202111,0.0,110741.0,8144.0,679360.0,483600.0,6303.0,120996.0,...,2868.0,3220.0,96254.0,15511.0,917.0,49.0,1548.0,545.0,2021-11-01,Nov-2021
23,202112,December 2021,202112,0.0,108903.0,5864.0,1420414.0,947791.0,6086.0,120772.0,...,886.0,3257.0,92925.0,19309.0,1038.0,80.0,1083.0,965.0,2021-12-01,Dec-2021
24,202201,January 2022,202201,0.0,107756.0,6832.0,1468551.0,851734.0,5777.0,119895.0,...,1044.0,3000.0,92751.0,18333.0,1175.0,42.0,2041.0,394.0,2022-01-01,Jan-2022
25,202202,February 2022,202202,0.0,100556.0,8155.0,474639.0,298847.0,5286.0,112456.0,...,1238.0,3778.0,101948.0,15520.0,1091.0,22.0,1261.0,401.0,2022-02-01,Feb-2022
26,202203,March 2022,202203,0.0,89804.0,6142.0,396547.0,241637.0,5360.0,98568.0,...,1079.0,3923.0,104061.0,17020.0,632.0,11.0,3967.0,72.0,2022-03-01,Mar-2022

In [12]:
features = ['Number_HIV_Positive_FP_Users',
            'Deliveries_in_unit_Live_births_less_than_2_5kg',
            'Bipolar_disorder',
            'Alcohol_Use_Disorder',
            'Tobacco_use',
            'Heart_failure',
            'Death_at_unit_Medical_emergencies',
            'Total_number_of_Deaths_in_Emergency_Unit',
            'Diabetes_mellitus_newly_diagnosed_Cases',
            'Diabetes_mellitus_newly_re_attendances_Cases',
            'Severe_Acute_Respiratory_Infection_SARI',
            'Severe_Pneumonia',
            'Diarrhoea_Acute',
            'Pneumonia',
            'Number_of_patients_accessing_emergency_unit_with_1hr_in_an_emergency_unit'
             ]

In [13]:
my_list = CEHS_all_cap.columns.values.tolist()
my_list

['periodid',
 'periodname',
 'periodcode',
 'perioddescription',
 'Mothers_who_initiated_breastfeeding_within_the_1st_hour_after_delivery_Total',
 'Number_HIV_Positive_FP_Users',
 'Deworming_1st_Dose',
 'Deworming_2nd_Dose',
 'Deliveries_in_unit_Live_births_less_than_2_5kg',
 'Deliveries_in_unit_Total',
 'Injuries_due_to_Gender_based_violence',
 'STI_due_to_Sexual_Gender_Based_Violence',
 'Abortions_due_to_GBV',
 'Anxiety_Disorders',
 'Anxiety_Disorder_due_to_gender_based_violence',
 'Unipolar_Depressive_Disorder',
 'Bipolar_disorder',
 'Alcohol_Use_Disorder',
 'Substance_Drug_use_Disorder',
 'Tobacco_use',
 'Number_of_emergency_cases_at_the_facility',
 'Patients_that_receive_care_at_the_scene_of_emergency',
 'Emergency_cases_that_arrive_at_the_facility_using_an_Ambulance',
 'Number_of_patients_accessing_emergency_unit_with_1hr_in_an_emergency_unit',
 'Total_number_of_Deaths_in_Emergency_Unit',
 'Death_at_unit_Medical_emergencies',
 'Death_at_unit_Obstetrics_gynaecology_emergencies',
 'Death_at_unit_Paediatric_emergencies',
 'Death_at_unit_Road_traffic_Injuries',
 'Death_at_unit_Poisoning',
 'CVA_Cases',
 'CVA_Deaths',
 'Heart_failure_Cases',
 'Heart_failure_Deaths',
 'Death_at_unit_Burns',
 'Diabetes_mellitus_newly_diagnosed_Cases',
 'Diabetes_mellitus_newly_diagnosed_Deaths',
 'Diabetes_mellitus_newly_re_attendances_Cases',
 'Diabetes_mellitus_newly_re_attendances_Deaths',
 'Pneumonia',
 'Severe_Pneumonia',
 'Severe_Acute_Respiratory_Infection_SARI',
 'Chronic_respiratory_diseases',
 'Dysentery',
 'Diarrhoea_Acute',
 'Typhoid_Fever',
 'Hypertension_newly_diagnosed_cases_Cases',
 'Hypertension_newly_diagnosed_cases_Deaths',
 'Heart_failure',
 'Death_at_unit_Surgical_emergencies',
 'period',
 'month_year']

In [14]:
def iqr_capping(df, cols, factor):
    
    for col in cols:
        q1 = df[col].quantile(0.25)
        q3 = df[col].quantile(0.75)
        
        iqr = q3 - q1
        
        upper_limit = q3 + (factor*iqr)
        lower_limit = q1 - (factor*iqr)
        
        df[col] = np.where(df[col]>upper_limit, upper_limit,np.where(df[col]<lower_limit, lower_limit, df[col]))

In [15]:
iqr_capping(CEHS_all_cap, features, 1.5)

In [16]:
matplotlib.rcParams['font.size'] = 15
sns.set(rc={'figure.figsize':(20,10)})

In [17]:
def date_change(df, col):
    df[col].replace({     'January 2020':'Jan-20', 
                          'February 2020':'Feb-20', 
                          'March 2020':'Mar-20', 
                          'April 2020':'Apr-20',
                          'May 2020':'May-20', 
                          'June 2020':'Jun-20', 
                          'July 2020':'Jul-20', 
                          'August 2020':'Aug-20',
                          'September 2020':'Sep-20', 
                          'October 2020':'Oct-20', 
                          'November 2020':'Nov-20', 
                          'December 2020':'Dec-20',
                          'January 2021':'Jan-21', 
                          'February 2021':'Feb-21', 
                          'March 2021':'Mar-21', 
                          'April 2021':'Apr-21',
                          'May 2021':'May-21', 
                          'June 2021':'Jun-21', 
                          'July 2021':'Jul-21', 
                          'August 2021':'Aug-21',
                          'September 2021':'Sep-21',
                          'October 2021':'Oct-21',
                          'November 2021':'Nov-21',
                          'December 2021':'Dec-21',
                          'January 2022':'Jan-22',
                          'February 2022':'Feb-22', 
                          'March 2022':'Mar-22', 
                          'April 2022':'Apr-22',
                          'May 2022':'May-22', 
                          'June 2022':'Jun-22', 
                          'July 2022':'Jul-22', 
                          'August 2022':'Aug-22',
                          'September 2022':'Sep-22',
                          'October 2022':'Oct-22',
                          'November 2022':'Nov-22',
                          'December 2022':'Dec-22'
                    }, inplace=True)

In [18]:
date_change(CEHS_all_cap, "periodname")

# Maternal

In [19]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Mothers_who_initiated_breastfeeding_within_the_1st_hour_after_delivery_Total"],
                    mode='lines+markers',
                    name='Mothers breastfeeding within the 1st hour after delivery'))
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Deliveries_in_unit_Total"],
                    mode='lines+markers',
                    name='Deliveries in unit'))

fig.update_layout(
    yaxis_title='Cases',
    xaxis_title='Months',
    title='Maternal')
fig.layout.template = 'simple_white'
fig.show()

In [20]:
fig = px.line(CEHS_all_cap, x='periodname', y='Number_HIV_Positive_FP_Users', markers = True,
              labels={
                     "periodname": "Month",
                     "Number_HIV_Positive_FP_Users": "Number HIV+ FP Users"
                       },
                title="Maternal")
fig.layout.template = 'simple_white'
fig.update_yaxes(range=[0, 10000])
fig.show()

# Child Health

In [21]:
def capping(df, cols):
    
    for col in cols:
              
        upper_limit = 2500000
        lower_limit = 0
        
        df[col] = np.where(df[col]>upper_limit, upper_limit,np.where(df[col]<lower_limit, lower_limit, df[col]))

In [22]:
features_deworming = ['Deworming_2nd_Dose']

In [23]:
capping(CEHS_all_cap, features_deworming)

In [24]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Deworming_1st_Dose"],
                    mode='lines+markers',
                    name='Deworming (1st Dose)'))
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Deworming_2nd_Dose"],
                    mode='lines+markers',
                    name='Deworming (2nd Dose)'))

fig.update_layout(
    yaxis_title='Doses',
    xaxis_title='Months',
    title='Deworming')
fig.layout.template = 'simple_white'
fig.show()

In [25]:
fig = px.line(CEHS_all_cap, x='periodname', y='Deliveries_in_unit_Live_births_less_than_2_5kg', markers = True,
              labels={
                     "periodname": "Month",
                     "Deliveries_in_unit_Live_births_less_than_2_5kg": "Live births - less than 2.5kg"
                       },
                title="Deliveries in unit")
fig.layout.template = 'simple_white'
fig.update_yaxes(range=[0, 7000])
fig.show()

# Gender Based Violence  and Abortions

In [26]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Abortions_due_to_GBV"],
                    mode='lines+markers',
                    name='Abortions due to GBV'))
fig.add_trace(go.Bar(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Anxiety_Disorder_due_to_gender_based_violence"],
                    name='Anxiety Disorder due to GBV'))

fig.update_layout(
    yaxis_title='Cases',
    xaxis_title='Months',
    title='Gender-Based Violence')
fig.layout.template = 'simple_white'
fig.show()

# Injury and sexual transmitted infections

In [27]:
fig = make_subplots(specs=[[{"secondary_y": True}]])

# Add traces

fig.add_trace(
    go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Abortions_due_to_GBV"],
               mode='lines+markers',marker_color='crimson',
               name="Abortions due to GBV"),
    secondary_y=False,
)

fig.add_trace(
    go.Bar(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["STI_due_to_Sexual_Gender_Based_Violence"], 
           name="STIs due to Sexual GBV",
           marker_color ='green',
           marker_line_width=1.5,
           marker_line_color='rgb(8,48,107)',
          opacity=0.5),
    secondary_y=True,
)


# Add figure title
fig.update_layout(
    title_text="Abortions and STIs due to GBV"
)

# Set x-axis title
fig.update_xaxes(title_text="Month")

# Set y-axes titles
fig.update_yaxes(title_text="<b>Abortions due to GBV</b>", secondary_y=False)
fig.update_yaxes(title_text="<b>STIs due to Sexual GBV</b>", secondary_y=True)
fig.layout.template = 'simple_white'
fig.show()

In [28]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["STI_due_to_Sexual_Gender_Based_Violence"],
                    mode='lines+markers',
                    name='STI due to Sexual GBV'))
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Injuries_due_to_Gender_based_violence"],
                    mode='lines+markers',
                    name='Injuries due to GBV'))

fig.update_layout(
    yaxis_title='Doses',
    xaxis_title='Months',
    title='Gender-Based Violence')
fig.layout.template = 'simple_white'
fig.update_yaxes(range=[0, 7000])
fig.show()

# Mental Health

In [29]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Anxiety_Disorders"],
                    mode='lines+markers',
                    name='Anxiety Disorders'))
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Bipolar_disorder"],
                    mode='lines+markers',
                    name='Bipolar disorder'))

fig.update_layout(
    yaxis_title='Doses',
    xaxis_title='Months',
    title='Gender-Based Violence')
fig.layout.template = 'simple_white'
fig.update_yaxes(range=[0, 7000])
fig.show()

In [30]:
fig = make_subplots(rows=2, cols=2,shared_xaxes=True,
                    vertical_spacing=0.1)
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Alcohol_Use_Disorder"],
                    mode='lines+markers',
                    name='Alcohol Use Disorder'),row=1, col=1)
fig.add_trace(go.Bar(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Substance_Drug_use_Disorder"],
                    
                    name='Substance (Drug) use Disorder'),row=1, col=2)
fig.add_trace(go.Bar(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Tobacco_use"],
                   
                    name='Tobacco use'),row=2, col=1)
fig.add_trace(go.Bar(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Unipolar_Depressive_Disorder"],
                   
                    name='Unipolar Depressive Disorder'),row=2, col=2)
fig.update_layout(title='Mental Health')
fig.layout.template = 'simple_white'
fig.show()

# Heart Conditions

In [31]:
fig = px.line(CEHS_all_cap, x='periodname', y='Heart_failure', markers = True,
              labels={
                     "periodname": "Month",
                     "Heart_failure": "Cases"
                       },
                title="Heart failure")
fig.layout.template = 'simple_white'
fig.update_yaxes(range=[0, 2100])
fig.show()

In [32]:
fig = go.Figure()
fig.add_trace(go.Bar(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Hypertension_newly_diagnosed_cases_Cases"],
                    name='Cases'))
fig.add_trace(go.Bar(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Hypertension_newly_diagnosed_cases_Deaths"],
                    name='Deaths'))

fig.update_layout(
    yaxis_title='Cases',
    xaxis_title='Months',
    title='Hypertension newly diagnosed cases')
fig.layout.template = 'simple_white'
fig.update_yaxes(range=[0, 1250])
fig.show()

# Ambulance & Emergency

In [33]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Number_of_emergency_cases_at_the_facility"],
                    mode='lines+markers',
                    name='Emergency cases'))
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Patients_that_receive_care_at_the_scene_of_emergency"],
                    mode='lines+markers',
                    name='Patients that receive care at the scene of emergency'))
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Emergency_cases_that_arrive_at_the_facility_using_an_Ambulance"],
                    mode='lines+markers',
                    name='Emergency cases that arrive using an Ambulance'))
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Number_of_patients_accessing_emergency_unit_with_1hr_in_an_emergency_unit"],
                    mode='lines+markers',
                    name='Patients accessing emergency unit with 1hr in an emergency unit'))
fig.update_layout(
    yaxis_title='Cases',
    xaxis_title='Months',
    title='Ambulance & Emergency')
fig.layout.template = 'simple_white'
#fig.update_yaxes(range=[0, 1250])
fig.show()

In [34]:
fig = make_subplots(rows=4, cols=1, shared_xaxes=True,       
    subplot_titles=("Emergency cases at the facility","Patients that receive care at the scene of emergency",
                    "Emergency cases that arrive using an Ambulance", 
                    "Patients accessing emergency unit with 1hr in an emergency unit"))
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Number_of_emergency_cases_at_the_facility"],
                    mode='lines+markers'),
              row=4, col=1)
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Patients_that_receive_care_at_the_scene_of_emergency"],
                    mode='lines+markers'),
              row=3, col=1)
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Emergency_cases_that_arrive_at_the_facility_using_an_Ambulance"],
                    mode='lines+markers'),
              row=2, col=1)
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Number_of_patients_accessing_emergency_unit_with_1hr_in_an_emergency_unit"],
                    mode='lines+markers'),
              row=1, col=1)
fig.update_layout(showlegend=False,
   title='Ambulance & Emergency')
fig.layout.template = 'simple_white'
fig.show()

In [35]:
fig = px.line(CEHS_all_cap, x='periodname', y='Total_number_of_Deaths_in_Emergency_Unit', markers = True,
              labels={
                     "periodname": "Month",
                     "Total_number_of_Deaths_in_Emergency_Unit": "Cases"
                       },
                title="Total number of Deaths in Emergency Unit")
fig.layout.template = 'simple_white'
fig.update_yaxes(range=[0, 420])
fig.show()

In [36]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Death_at_unit_Medical_emergencies"],
                    mode='lines+markers',
                    name='Medical emergencies'))
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Death_at_unit_Obstetrics_gynaecology_emergencies"],
                    mode='lines+markers',
                    name='Obstetrics/gynaecology emergencies'))
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Death_at_unit_Paediatric_emergencies"],
                    mode='lines+markers',
                    name='Paediatric emergencies'))
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Death_at_unit_Road_traffic_Injuries"],
                    mode='lines+markers',
                    name='Road traffic Injuries'))
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Death_at_unit_Poisoning"],
                    mode='lines+markers',
                    name='Poisoning'))
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Death_at_unit_Burns"],
                    mode='lines+markers',
                    name='Burns'))
fig.update_layout(
    yaxis_title='Deaths',
    xaxis_title='Months',
    title='Death at unit')
fig.layout.template = 'simple_white'
fig.show()

In [37]:
fig = make_subplots(rows=3, cols=2, shared_xaxes=True,       
    subplot_titles=("Medical emergencies","Obstetrics/gynaecology emergencies",
                    "Paediatric emergencies", "Road traffic Injuries",
                    "Poisoning", "Burns"))
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Death_at_unit_Medical_emergencies"],
                    mode='lines+markers'),
                    row=1, col=1)
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Death_at_unit_Obstetrics_gynaecology_emergencies"],
                    mode='lines+markers'),
                    row=1, col=2)
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Death_at_unit_Paediatric_emergencies"],
                    mode='lines+markers'),
                    row=2, col=1)
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Death_at_unit_Road_traffic_Injuries"],
                    mode='lines+markers'),
                    row=2, col=2)
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Death_at_unit_Poisoning"],
                    mode='lines+markers'),
                    row=3, col=1)
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Death_at_unit_Burns"],
                    mode='lines+markers'),
                    row=3, col=2)
fig.update_layout(showlegend=False,
   title='Death at unit')
fig.layout.template = 'simple_white'
fig.show()

# Diabetes

In [38]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Diabetes_mellitus_newly_diagnosed_Cases"],
                    mode='lines+markers',
                    name='Diagnosed'))
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Diabetes_mellitus_newly_re_attendances_Cases"],
                    mode='lines+markers',
                    name='Re-attendances'))
fig.update_layout(
    yaxis_title='Cases',
    xaxis_title='Months',
    title='Diabetes mellitus(newly)')
fig.layout.template = 'simple_white'
fig.show()

In [39]:
fig = go.Figure()
fig.add_trace(go.Bar(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Diabetes_mellitus_newly_diagnosed_Deaths"],
                    name='Diagnosed'))
fig.add_trace(go.Bar(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Diabetes_mellitus_newly_re_attendances_Deaths"],
                    name='Re-attendances'))

fig.update_layout(
    yaxis_title='Deaths',
    xaxis_title='Months',
    title='Diabetes mellitus(newly)')
fig.layout.template = 'simple_white'
fig.show()

In [40]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Severe_Acute_Respiratory_Infection_SARI"],
                    mode='lines+markers',
                    name='SARI'))
fig.add_trace(go.Bar(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Chronic_respiratory_diseases"],
                    name='Chronic respiratory diseases'))

fig.update_layout(
    yaxis_title='Cases',
    xaxis_title='Months',
    title='Respiratory diseases')
fig.layout.template = 'simple_white'
fig.show()

In [41]:
fig = make_subplots(specs=[[{"secondary_y": True}]])

# Add traces
fig.add_trace(
    go.Bar(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Diabetes_mellitus_newly_diagnosed_Deaths"], name="Diagnosed Deaths",
           marker_color ='blue',
           marker_line_width=1.5,
           marker_line_color='rgb(8,48,107)',
          opacity=0.5),
    secondary_y=True,
)
fig.add_trace(
    go.Bar(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Diabetes_mellitus_newly_re_attendances_Deaths"], name="Re-attendances Deaths",
           marker_color ='green',
           marker_line_width=1.5,
           marker_line_color='rgb(8,48,107)',
          opacity=0.5),
    secondary_y=True,
)
fig.add_trace(
    go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Diabetes_mellitus_newly_diagnosed_Cases"],
               mode='lines+markers',marker_color='#9c179e',
               name="Diagnosed Cases"),
    secondary_y=False,
)

fig.add_trace(
    go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Diabetes_mellitus_newly_re_attendances_Cases"],
               mode='lines+markers',marker_color='crimson',
               name="Re-attendances Cases"),
    secondary_y=False,
)

# Add figure title
fig.update_layout(
    title_text="Diabetes mellitus(newly)"
)

# Set x-axis title
fig.update_xaxes(title_text="Month")

# Set y-axes titles
fig.update_yaxes(title_text="<b>Deaths</b>", secondary_y=True)
fig.update_yaxes(title_text="<b>Cases</b>", secondary_y=False)
fig.layout.template = 'simple_white'
fig.show()

# SARI,Pneumonia

In [42]:
fig = make_subplots(specs=[[{"secondary_y": True}]])

# Add traces

fig.add_trace(
    go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Pneumonia"],
               mode='lines+markers',marker_color='crimson',
               name="Pneumonia"),
    secondary_y=False,
)

fig.add_trace(
    go.Bar(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Severe_Pneumonia"], name="Severe Pneumonia",
           marker_color ='green',
           marker_line_width=1.5,
           marker_line_color='rgb(8,48,107)',
          opacity=0.5),
    secondary_y=True,
)


# Add figure title
fig.update_layout(
    title_text="Respiratory diseases"
)

# Set x-axis title
fig.update_xaxes(title_text="Month")

# Set y-axes titles
fig.update_yaxes(title_text="<b>Pneumonia</b>", secondary_y=False)
fig.update_yaxes(title_text="<b>Severe Pneumonia</b>", secondary_y=True)
fig.layout.template = 'simple_white'
fig.show()

# Dysentery,Typhoid

In [43]:
fig = make_subplots(specs=[[{"secondary_y": True}]])

# Add traces
fig.add_trace(
    go.Bar(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Dysentery"], name="Dysentery",
           marker_color ='green',
           marker_line_width=1.5,
           marker_line_color='rgb(8,48,107)',
          opacity=0.5),
    secondary_y=True,
)
fig.add_trace(
    go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Typhoid_Fever"],
               mode='lines+markers',
               name="Typhoid Fever"),
    secondary_y=False,
)

fig.add_trace(
    go.Scatter(x=CEHS_all_cap["periodname"], y=CEHS_all_cap["Diarrhoea_Acute"],
               mode='lines+markers',marker_color='crimson',
               name="Diarrhoea(Acute)"),
    secondary_y=False,
)

# Add figure title
fig.update_layout(
    title_text="Other diseases"
)

# Set x-axis title
fig.update_xaxes(title_text="Month")

# Set y-axes titles
fig.update_yaxes(title_text="<b>Dysentery</b>", secondary_y=True)
fig.update_yaxes(title_text="<b>Typhoid Fever and Diarrhoea(Acute)</b>", secondary_y=False)
fig.layout.template = 'simple_white'
fig.show()

In [44]:
# ax.set_ylim(0, max(CEHS_all_cap.Total_number_of_Deaths_in_Emergency_Unit))